### ISSUE TITLE
Maybe more detailed robustness results on AlexNet?

### ISSUE THREAD

**Issue by yuxinWen** [hendrycks/robustness#10]
We're interested in studying the behavior of DNNs on ImageNet-C in more detail. However, we noticed that we cannot find the robust results of severity at each level  for AlexNet even in Table 2. So could you provide these results at your convenience? Thanks!

**Comment by yuxinWen** [comment]
Thanks a lot!

**Comment by double-fire-0** [comment]
> Here are the AlexNet error rates at different severities.
> 
> Gaussian
> =Average(0.69528, 0.82542, 0.93554, 0.98138, 0.99452)
> Shot
> =Average(0.71224, 0.85108, 0.93574, 0.98182, 0.99146)
> Impulse
> =Average(0.78374, 0.89808, 0.9487, 0.9872, 0.99548)
> 
> Defocus
> =Average(0.656239999999999, 0.73202, 0.85036, 0.91364, 0.94714)
> Glass
> =Average(0.64308, 0.75054, 0.88806, 0.91622, 0.93344)
> Motion
> =Average(0.5843, 0.70048, 0.82108, 0.8975, 0.92638)
> Zoom
> =Average(0.70008, 0.769919999999999, 0.80784, 0.84198, 0.87198)
> 
> Snow
> =Average(0.71726, 0.88392, 0.86468, 0.9187, 0.94952)
> Frost
> =Average(0.6139, 0.797339999999999, 0.8879, 0.89942, 0.9343)
> Fog
> =Average(0.67474, 0.7605, 0.84378, 0.8726, 0.945)
> Brightness
> =Average(0.4514, 0.48502, 0.54048, 0.62166, 0.724399999999999)
> 
> Contrast
> =Average(0.64548, 0.7615, 0.88874, 0.9776, 0.9927)
> Elastic
> =Average(0.52596, 0.70116, 0.55686, 0.64076, 0.80554)
> Pixelate
> =Average(0.52218, 0.5462, 0.737279999999999, 0.87092, 0.91262)
> JPEG
> =Average(0.510019999999999, 0.54718, 0.57294, 0.654579999999999, 0.74778)
> 
> Speckle Noise
> =Average(0.66192, 0.7444, 0.90246, 0.94548, 0.97268)
> Gaussian Blur
> =Average(0.54732, 0.70444, 0.82574, 0.89864, 0.9594)
> Spatter
> =Average(0.47196, 0.621939999999999, 0.75052, 0.84132, 0.90182)
> Saturate
> =Average(0.59342, 0.65514, 0.51174, 0.70834, 0.8226)

Could you please provide the result of AlexNet on ImageNet-P?
Thanks
