### ISSUE TITLE
Reason behind the different values of C for different dataset ?

### ISSUE THREAD

**Issue by bibhutibhusans** [hendrycks/robustness#12]
def gaussian_noise(x, severity=1):
    **c = [.08, .12, 0.18, 0.26, 0.38]**[severity - 1]
    x = np.array(x) / 255.
    return np.clip(x + np.random.normal(size=x.shape, scale=c), 0, 1) * 255

The similar function is defined in multiple files but with a different C value. What is the reason behind it and how was it calculated ?

**Comment by hendrycks** [comment]
There are five C values corresponding to five corruption severities. The values were initially chosen so that the MS-SSIM(x, corruption_s(x)) = 1 - s/10 for severity s \in \{1, 2, 3, 4, 5\}. Since MS-SSIM is not a perfect measure I used some discretion.

**Comment by bibhutibhusans** [comment]
Thank you for your response!

I found here a code for calculating MS-SSIM:
 [https://github.com/tensorflow/models/blob/f87a58cd96d45de73c9a8330a06b2ab56749a7fa/research/compression/image_encoder/msssim.py]

In the definition of "_SSIMForMultiScale" the Structural Similarity Map between `img1` and `img2` is calculated. 

The question is: 
- Did you use a similar approach and parameters to calculate the MS-SSIM?
- Did you calculate the mean and standard deviation over the whole data set or was done for each picture?

Thanks a lot in advance.

**Comment by hendrycks** [comment]
Yes, I think I used the tensorflow MS-SSIM code and looked at a small sample of images. However, the current severity levels probably do not track the MS-SSIM well since I used the MS-SSIM just as the starting point.
