### ISSUE TITLE
Applying corruption in memory vs compressed images

### ISSUE THREAD

**Issue by lukas-schott** [hendrycks/robustness#14]
The authors of https://arxiv.org/pdf/1901.10513.pdf (section 6, 2nd paragraph) claim that there is a significant difference between the distorted images provided by the link in the ReadMe and applying the corruptions in memory to create the ImageNet-C dataset due to jpeg compression. 

Which one should be used now?
Has this problem been resolved?

**Comment by hendrycks** [comment]
In the paper we state
"ImageNet-C images are saved as lightly compressed JPEGs; this implies an image corrupted by Gaussian noise is also slightly corrupted by JPEG compression."
Using JPEGs also makes evaluation deterministic. We provide a way to apply corruptions in memory for convenience.
