### ISSUE TITLE
CIFAR-10-C state-of-the-art?

### ISSUE THREAD

**Issue by AngusG** [hendrycks/robustness#19]
Hi, not an issue per-se but just wondering if this information is tracked anywhere? I couldn't find any baselines in the original paper. Is it fair to say that 76.9% test acc from https://arxiv.org/abs/1906.12340 represents the state-of-the-art? This work https://arxiv.org/abs/1906.02611 seems to be a close runner up with 96.2 base * 0.797 mCE = 76.7%.

**Comment by hendrycks** [comment]
Around 77% is approximately SOTA. I didn't include baselines for every version of the dataset since there are so many versions.

**Comment by wetliu** [comment]
Thank you for your question and answer. I am wondering where the code for CIFAR-10-C evaluation on this repo for your ~77% acc (though I found CIFAR10/100-P evaluation)?

**Comment by hendrycks** [comment]
Does https://github.com/google-research/augmix/blob/master/cifar.py#L266 work
for you?

**Comment by wetliu** [comment]
I think it should and I will post here if I have further questions. Thank you so much!
