### ISSUE TITLE
CIFAR-100-C?

### ISSUE THREAD

**Issue by rsluo** [hendrycks/robustness#21]
Do you also have a copy of CIFAR-100-C that we could download? I didn't see one linked in the readme file. Thanks!

**Comment by rsluo** [comment]
Also, I noticed that in CIFAR-10-C, each numpy file has 50,000 images. Do these correspond to the training set of CIFAR-10? Thank you!

**Comment by hendrycks** [comment]
CIFAR-100-C is available through Google Drive. The 50K images are the 10K
test images of 5 different severities.

**Comment by rsluo** [comment]
Ok, thank you! Are they in order? (i.e. the first 10,000 indices are the
lowest severity and the last 10,000 are the highest?)

**Comment by hendrycks** [comment]
Yes
