### ISSUE TITLE
About 'difficulty' in imagenet-p 

### ISSUE THREAD

**Issue by taekwan-lee** [hendrycks/robustness#23]
Looking over the code https://github.com/hendrycks/robustness/blob/master/ImageNet-P/create_p/make_imagenet_p.py, I came up with some questions.

1) In `make_imagenet_p.py`, `gaussian noise`, `shot noise` and `speckle noise` have three different 'levels' which I guess is 'difficulty' mentioned in the paper. When calculating mFR or mT5D for imagenet-p, should the three different difficulties for the three noises be taken into account as well?

2) I guess the weights used for noises with difficulty levels vary from dataset to dataset.
 For example, in `make_imagenet_p.py`, 0.03, 0.05 and 0.08 are used for gaussian noise weights, whereas in `make_cifar_p.py`, 0.02, 0.04 and 0.06 are used. Are these values determined with any rules?
 If I want to make -p data with some new datasets, can I just use the weight values for imagenet-p?

**Comment by hendrycks** [comment]
Most people only measure with difficulty 1. For example, in https://github.com/google-research/augmix (released tomorrow) we use difficulty 1. The values were not chosen by any particular formula and were chosen by hand.
