### ISSUE TITLE
Question about Relative Corruption Error

### ISSUE THREAD

**Issue by heytitle** [hendrycks/robustness#24]
Hi,

May I ask a question question regarding the Relative Corruption Error?

<img width="815" alt="image" src="https://user-images.githubusercontent.com/1214890/71534954-9550df00-2902-11ea-9253-89a58b2f81fb.png">

Do I understand correctly that here we sum all the level errors first before subtracting E^{Network}_{Clean}? Or we subtract each level error by the clean error and then sum?

Thank you in advance for you answer!

**Comment by hendrycks** [comment]
Here is a spreadsheet with example computations. The Relative mCE is in the second tab. https://docs.google.com/spreadsheets/d/1WpwRBGW5gvGnQHZfObZp_MRSAKz_FoMzCuqlRmk4lLI/edit?usp=sharing
