### ISSUE TITLE
Access to Imagenet-P dataset

### ISSUE THREAD

**Issue by AIprogrammer** [hendrycks/robustness#30]
Hi, thanks for your sharing the code and project. Through the urls in the readme, the speed of downloading the dataset is very slow, could you share the dataset through google drive. etc.

**Comment by hendrycks** [comment]
It is shared through Google Drive. https://drive.google.com/drive/folders/1vRrDaWA6-_GaUZqOmovWrr4W34aiSLu7?usp=sharing
