### ISSUE TITLE
Testing the images which is generated online

### ISSUE THREAD

**Issue by AIprogrammer** [hendrycks/robustness#31]
Hi, I wonder if we do not generated the corrputed images offline, how can we avoid the difference of evaluation results?  In other words, if we do the evaluation and corrupt the images at the same time（ such as in dataloader simillar to data augmentation) , will the accuracy of a same model differ a lot in each evaluation?

**Comment by hendrycks** [comment]
It should not vary much since the sample size is large, but downloading the images is faster than computing the corruptions.

**Comment by AIprogrammer** [comment]
Hi, thanks for your reply. Should we set random seed while generating the corrupted images?

**Comment by hendrycks** [comment]
I don't think that will make a difference since there is not a canonical seed.

**Comment by AIprogrammer** [comment]
OK, got it, thanks.
