### ISSUE TITLE
Where is 'calib_err' function?

### ISSUE THREAD

**Issue by ildoonet** [hendrycks/robustness#33]
I can not find 'calib_err' in cifar-p evaluation code.

Where is it?

**Comment by hendrycks** [comment]
Hi. Thank you for your interest. I have a calib_err function here:
https://github.com/hendrycks/natural-adv-examples/blob/master/calibration_tools.py#L4
Hopefully this helps. ([Also, here is an additional new dataset for testing robustness which isn't on arXiv yet.](https://github.com/hendrycks/imagenet-r))
