### ISSUE TITLE
Better ResNet50 Baseline

### ISSUE THREAD

**Issue by Justinhzy** [hendrycks/robustness#35]
Hi, I got a 61% mCE and the same clean error for the resnet50 ImgNet-c baseline using this code. Much better than 76.7%. Did I get right?

**Comment by hendrycks** [comment]
I assume you're not normalizing by AlexNet's error rate to compute the mCE.
https://docs.google.com/spreadsheets/d/1RwqofJPHhtdRPG-dDO7wPp-aGn-AmwmU5-rpvTzrMHw/edit?usp=sharing
Is that correct?
