### ISSUE TITLE
Additional four corruptions

### ISSUE THREAD

**Issue by ildoonet** [hendrycks/robustness#36]
https://github.com/hendrycks/robustness/blob/master/ImageNet-C/imagenet_c/imagenet_c/__init__.py#L5

In your papers (robustness, augmix), you used 15 corruptions.
Here, the above line of the code, you can see 19 corruptions listed in a tuple.
This might be un-clear to many people, including me. The last four corruptions should be removed so that one can test a model with corruptions as listed in your paper.

**Comment by hendrycks** [comment]
Those are validation corruptions.

**Comment by ildoonet** [comment]
@hendrycks Thanks for the quick reply. After listening to you, I checked the paper again and understood it. But still, it is might be confusing anyone. I think you need to add a comment or split the list into multiples.

Now that I know why there are 19 corruptions, I'm closing this issue. Thanks!
