### ISSUE TITLE
The baseline results of AlexNet is not optimal

### ISSUE THREAD

**Issue by JGyoung33** [hendrycks/robustness#38]
Hello,

I also train a baseline method and use AlexNet to evaluate corrupted images, but it's different from the AlexNet results in "BENCHMARKING NEURAL NETWORK ROBUSTNESS TO COMMON CORRUPTIONS AND PERTURBATIONS. " 

We have similar performance on clean images, but I acquire better results on corrupted images than you. It's so weird.

**Comment by hendrycks** [comment]
Hi,
We used the torchvision pretrained model. If you used a different training method to train AlexNet, then I think there is not an issue.

**Comment by JGyoung33** [comment]
> Hi,
> We used the torchvision pretrained model. If you used a different training method to train AlexNet, then I think there is not an issue.

Thank you.
