### ISSUE TITLE
Frost missing after pip install

### ISSUE THREAD

**Issue by nottombrown** [hendrycks/robustness#4]
After pip installing, frost is not available
```
  File "/root/code/robustness/ImageNet-C/imagenet_c/imagenet_c/__init__.py", line 29, in corrupt
    x_corrupted = corruption_dict[corruption_name](Image.fromarray(x), severity)
  File "/root/code/robustness/ImageNet-C/imagenet_c/imagenet_c/corruptions.py", line 259, in frost
    x_start, y_start = np.random.randint(0, frost.shape[0] - 224), np.random.randint(0, frost.shape[1] - 224)
AttributeError: 'NoneType' object has no attribute 'shape'
```
Likely a path error?

**Comment by hendrycks** [comment]
Hopefully commit 20caed9 is sufficient.

**Comment by nottombrown** [comment]
Hmm, I'm still seeing an issue from Travis (although it's working locally for me)

https://travis-ci.org/google/unrestricted-adversarial-examples/jobs/437416153#L794

**Comment by hendrycks** [comment]
When I install with ```pip install imagenet-c```, it is broken. When I install ```pip install -e .```, all is fine.
