### ISSUE TITLE
Not all corruption methods are available in make_imagenet_64_c.py

### ISSUE THREAD

**Issue by wetliu** [hendrycks/robustness#42]
Hello. Thank you for providing the code for corruption. 

Are there any specific reasons some corruption methods are commented out where some are left in [make_imagenet_64_c.py
](https://github.com/hendrycks/robustness/blob/master/ImageNet-C/create_c/make_imagenet_64_c.py)?

For example:
```
# d['Motion Blur'] = motion_blur
# d['Zoom Blur'] = zoom_blur
# d['Snow'] = snow
d['Frost'] = frost
d['Fog'] = fog
d['Brightness'] = brightness
d['Contrast'] = contrast
```

Thank you so much!

**Comment by hendrycks** [comment]
No.

**Comment by wetliu** [comment]
Can I use the commented corruptions, such as Gaussian noise provided?

**Comment by hendrycks** [comment]
Yes
