### ISSUE TITLE
Do you have clean images corresponding ImageNet-C data or transform method

### ISSUE THREAD

**Issue by mjmjeong** [hendrycks/robustness#44]
I want to compute PSNR with refined corrupted images and clean images. 
However, ILSVRC2012/val/images differ from ImageNet-C with scale and cropped. 

1. Could you give the transformation method from ImageNet to ImageNet-C in the concept of **scale/crop.** 
 (Just conducting resize(256) and center crop(224) is not fit for imagenet-C :(  ) 
2.  Or could you give the validation datasets(clean images) corresponding to the ImageNet-C.

**Comment by Manasdatakalp** [comment]
hi, where can i find the clean images
