### ISSUE TITLE
Crops are not consistent across corruptions

### ISSUE THREAD

**Issue by hutec** [hendrycks/robustness#47]
We realized that the crops across different corruptions in the ImageNet-C dataset are not the same.

For example  `contrast/1/n016443737ILSVRC2012_val_00023855.JPEG` vs `impulse_noise/1/n016443737ILSVRC2012_val_00023855.png`

Apart from different file types, the `impulse_noise` image (right) seems to be only resized instead of cropped?

![image](https://user-images.githubusercontent.com/5879015/119507978-9e501500-bd6f-11eb-9a97-dcf54293f328.png)

**Comment by hendrycks** [comment]
That's strange and I am not sure the cause. It's too late to change it now, but that's a very subtle find!

**Comment by YunanZhu** [comment]
I checked the image `impulse_noise/1/n01644373/ILSVRC2012_val_00023855.JPEG`:
![ILSVRC2012_val_00023855](https://user-images.githubusercontent.com/49200936/133015488-77599d06-682b-4d1b-abd3-d5a4b9f44479.JPEG)

I think the crops are consistent. Notice that your `impulse_noise` image is `.png`, it may be generated by your own code.
