### ISSUE TITLE
Different Image Size

### ISSUE THREAD

**Issue by vchiley** [hendrycks/robustness#52]
The [reference test script](https://github.com/hendrycks/robustness/blob/master/ImageNet-C/test.py) operates on an [img size of 224](https://github.com/hendrycks/robustness/blob/master/ImageNet-C/test.py#L211).
Something like the [EfficientNet models](https://paperswithcode.com/method/efficientnet) scale the input resolution as the network is scaled. If I want to test the EfficientNet models against corruption would I only be able to test input resolution 224 or can I just scale the input resolution to the standard input size used by the different EfficientNet scales?

Note: there seems to be a discrepancy in how "clean" vs "distorted" images are loaded.
The [clean images are resized to img size 256, then a 224 center crop happens](https://github.com/hendrycks/robustness/blob/master/ImageNet-C/test.py#L211).
The [distorted images are just center cropped to 224 regardless of the input img size...](https://github.com/hendrycks/robustness/blob/master/ImageNet-C/test.py#L244).
Unless, during the creation of the dataset, the images are all converted to img size 256?

**Comment by hendrycks** [comment]
We have a 299x299 version available for download. https://drive.google.com/drive/folders/1FR7UsoPXxj5-Fa1UOBdkt3OrlrySImJb?usp=sharing

**Comment by vchiley** [comment]
Thank you for the reply, but I don't think it really addresses the issue.
EfficientNet's input image size spans from 224 to 600 (specifically its 224, 240, 260, 300, 380, 456, 528, 600).
Would maybe the more correct answer be: use the [make_c script](https://github.com/hendrycks/robustness/blob/master/ImageNet-C/create_c/make_imagenet_c.py) (modifying [this line](https://github.com/hendrycks/robustness/blob/master/ImageNet-C/create_c/make_imagenet_c.py#L583)) and make any input size I want?

**Comment by hendrycks** [comment]
You could do that if you would want. We do not intend to make an ImageNet-C
version for every image resolution. We provided pre-made images for easier
use and comparability.

**Comment by vchiley** [comment]
Followup question: is robustness to corruption comparable at different image resolutions?

**Comment by hendrycks** [comment]
I do not think they are directly comparable since a fixed standard deviation of Gaussian noise is more destructive for smaller images than larger images.
