### ISSUE TITLE
CIFAR-100-C Zenodo download link not working

### ISSUE THREAD

**Issue by mikelzc1990** [hendrycks/robustness#54]
Dear authors, 

Could you please kindly provide another link (Google Drive or Dropbox) for downloading the CIFAR-100-C? 

Thanks in advance

**Comment by hendrycks** [comment]
That may have been a temporary issue with Zenodo since it appears to be working currently. Here is a mirror in case it does not: https://drive.google.com/drive/folders/1SnijDn2h5pdUp8XyRGrL858eALMIeThq?usp=sharing
