### ISSUE TITLE
Question about the paper formula

### ISSUE THREAD

**Issue by wetliu** [hendrycks/robustness#56]
Hello. Thank you for the great work. 

Should the equation defining the corruption robustness be Ec∼C[P(x,y)∼D(f(c(x)) = y)] instead of Ec∼C[P(x,y)∼D(f(c(x) = y))]? 

If it should not, would you mind explaining what it means by c(x) = y?

Thank you so much!

**Comment by hendrycks** [comment]
f(c(x)) = y
f is the classifier; c is the corruption function; x is the original image
before corruption; if f(c(x)) = y, then that means the classifier f
correctly classified the corrupted image c(x)

**Comment by wetliu** [comment]
Thank you so much for your clarification!
