### ISSUE TITLE
CIFAR-10-C Train or Test Set?

### ISSUE THREAD

**Issue by collinskatie** [hendrycks/robustness#57]
Thank you for making this repository available! I'm hoping to work with the CIFAR-10-C set and just downloaded the .tar available here (https://zenodo.org/record/2535967#.YrMov5DMLX0). 

The docs note this is the CIFAR-10 test set. However, when I read in the labels.npy file (or other *.npy files, such as the Gaussian blur one), there appear to be 50,000 images. Which I think would be the train set instead? 

The docs imply there would only be 20,000 imgs in the .npy (and 10,000 for the labels) if there was a different degree of corruption used for the test set.

I just wanted to check then if the .tar contains the CIFAR-10 train set? And/or how to get access to the corrupted test set? Thank you, and apologies if I've misinterpreted any of this!

**Comment by hendrycks** [comment]
> The docs note this is the CIFAR-10 test set. However, when I read in the
labels.npy file (or other *.npy files, such as the Gaussian blur one),
there appear to be 50,000 images. Which I think would be the train set
instead?

There are five corruption severities, hence there are 5 * 10K = 50K
examples.

**Comment by collinskatie** [comment]
I see, I misunderstood. That makes sense now! Thanks for clarifying, @hendrycks !
