### ISSUE TITLE
how to use clahe in preprocess? 

### ISSUE THREAD

**Issue by bei-startdt** [hendrycks/robustness#9]
##### I tried two usage:
1.
```
clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
for i in range(3):
    img[:,:,i] = clahe.apply(img[:,:,i]) 
```
2. 
```
clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
frame = cv2.cvtColor(frame, cv2.COLOR_BGR2LAB)
frame[:,:,0] = clahe.apply(frame[:,:,0])
frame = cv2.cvtColor(frame, cv2.COLOR_LAB2BGR)
```
* for the one part, I don't know which usage is correct
* for the other, I don't know which number clipLimit,tileGridSize should be set

Could you help me with the answer?
Thanks

**Comment by hendrycks** [comment]
I used CLAHE from skimage.exposure.equalize_adapthist. That implementation has rescaling which cv2 does not have. However cv2 is much faster, so an implementation with cv2 can look like this:

```
def rescale(x):
    x_min, x_max = x.min(), x.max()
    return np.uint8(np.clip((x - x_min)/float(x_max - x_min + 1e-8), 0, 1) * 255)


clahe = cv2.createCLAHE(clipLimit=2 tileGridSize=(8, 8))


class HistEq(object):
    # def __init__(self):

    def __call__(self, x):
        x = cv2.cvtColor(np.array(x), cv2.COLOR_RGB2LAB)
        l = x[:,:,0]
        lmin, lmax = l.min(), l.max()
        return cv2.cvtColor(np.concatenate((clahe.apply(np.uint8((l - lmin) / (lmax - lmin + 1e-8) * 255))[...,None], x[:,:,1:]), axis=2),
                            cv2.COLOR_LAB2RGB)
```

I can e-mail you the weights for the model if you want.
As it happens, [I recently updated the paper](https://openreview.net/pdf?id=HJz6tiCqYm) to mention a more exciting technique that beats CLAHE significantly. Fine-tuning with "Stylized ImageNet" significantly outperforms fine-tuning with CLAHE applied to images.

**Comment by bei-startdt** [comment]
Thank U very much.
